[#153159] Handle missing attributes when updating from LDAP (#2446)
# Release Notes

It is possible that some users may be missing email or other required attributes in the LDAP response.  When updating all unexpired users with this rake task, we want to log the errors and keep going.

The error I saw while testing on staging is:
`NoMethodError (undefined method 'mail' for #<Net::LDAP::Entry:0x000000000b71b398>)`