[#132878] Fix default Sanger batch download
The plate_mode argument is coming in as either nil or a blank string
because it’s coming from the `group` field on batches. That was causing
`NoMethodError: undefined method `keys' for #<String:0x00000009d8b6f8>`
on production, and a missing translation in development.