Fix typo in canceled_statuses_for_facility and add spec coverage (#3220)
# Release Notes

Addresses https://rollbar.com/tablexi/nucore-nu/items/823/.
```
NameError: undefined local variable or method `current_facility' for #<Class:0x000000000adb9610>
```

introduced in [this](https://github.com/tablexi/nucore-open/pull/3156/files#diff-ef96217bf42a44cb4eba3a75f27db3dbe91e46dc9d9486b60a649f37fb2164b8R58) commit