[#103115] Fix error on next_available not found for admin reservation
`facility_reservations#new (NoMethodError) "undefined method `reserve_interval' for nil:NilClass"`

When @instrument.next_available_reservation is nil