[#136836/#136829] 500 when reservation has `:base` errors (#1141)
First ticket number is NU, second is UIC.

An error like “The reservation conflicts with another reservation.” was
erroring with

```
An ActionView::Template::Error occurred in order_details#update:

undefined method `humanize' for nil:NilClass
app/views/order_management/order_details/_warnings.html.haml:14:in
`_app_views_order_management_order_details__warn
```

The `errors` was getting an empty string for a key:
` @messages=
{:""=>
["The reservation conflicts with another reservation.",
"The reservation spans time that the instrument is unavailable for
reservation"]}>`

This would then choke when trying to call `full_messages`