[#143771] Prevent error on invalid dates on Reservation#update
Prevents a "NoMethodError: undefined method `<' for nil:NilClass" when start/end at is blank because of invalid data.